### PR TITLE
single report example

### PR DESCRIPTION
**Pull request by jmontleon**
Alex, take a look here. I'm not convinced everything I've moved/renamed is for the better, but it should demonstrate how to get it all into one report.

### CODE REVIEW

**Comment by jmontleon** [comment]
```
{
	"cluster": {
		"namespaces": [{
			"name": "kube-system",
			"pods": [{
				"name": "master-api-192.168.122.30.nip.io"
			}]
		}],
		"pvs": [{
			"name": "11"
		}]
	},
	"components": [{
		"component": "Crio",
		"reports": [{
			"name": "Docker",
			"kind": "Container Runtime",
			"supported": false,
			"confidence": 0,
			"comment": "The Docker runtime has been replaced with CRI-O"
		}]
	}]
}
```

**Comment by jmontleon** [comment]
@eriknelson from a UX perspective does the json above look like something reasonable to parse into an HTML report?

**Comment by jmontleon** [comment]
I think the build failure is just because I didn't fix the tests.

**Comment by eriknelson** [comment]
@jmontleon yeah definitely. It would be pretty easy to write a script that basically renders that into some html templates if that's the approach you wanted to take.

**Pull request merged**
